services:
  mariadb:
    build:
      context: ./srcs/requirements/mariadb
    container_name: mariadb
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    secrets:
      - db_user
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  wordpress:
    build:
      context: ./srcs/requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - DB_HOST=mariadb
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DOMAIN_NAME=${DOMAIN_NAME}
    secrets:
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped

  nginx:
    build:
      context: ./srcs/requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/abbenmou/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/abbenmou/data/wordpress

networks:
  inception:
    driver: bridge

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  wp_admin_user:
    file: ./secrets/wp_admin_user.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_admin_email:
    file: ./secrets/wp_admin_email.txt